export interface StockProposal {
  id: string;
  producer_name: string;
  producer_cpf: string | null;
  credit_program: string | null;
  estimated_value: number | null;
  notes: string | null;
  agency_id: string;
  created_by: string;
  status: string;
  created_at: string;
  updated_at: string;
  // CSV import fields
  pendencias: string | null;
  serasa: string | null;
  cliente_renovacao: string | null;
  ano_contrato: string | null;
  agencia_cadastro: string | null;
  municipio: string | null;
  linha_credito: string | null;
  localizacao: string | null;
  observacoes_extra: string | null;
  original_csv_status: string | null;
  projetista: string | null;
  order_index: number;
  entry_date?: string | null;
  producer_address?: string | null;
  producer_phone?: string | null;
  pronaf_line?: string | null;
  sicad?: string | null;
  request_type?: string | null;
  agency_code?: string | null;
  agency_name?: string | null;
  task?: string | null;
  central_date?: string | null;
  activity_start_date?: string | null;
  last_analyst?: string | null;
  owner?: string | null;
  originator?: string | null;
  current_state?: string | null;
  category?: string | null;
  client_size?: string | null;
  proposal_number?: string | null;
  credit_purpose?: string | null;
  resource_application?: string | null;
  special_treatment?: string | null;
  central?: string | null;
  superintendence_code?: string | null;
  superintendence_name?: string | null;
  microcredit?: string | null;
  renegotiation_type?: string | null;
  guarantee_type?: string | null;
  registration_central_task?: string | null;
  registration_central_activity_start?: string | null;
  judicial_period?: string | null;
  requesting_unit?: string | null;
  agreement?: string | null;
  culture?: string | null;
  roc_type?: string | null;
  poa_prd_subject?: string | null;
  activity_id?: string | null;
  technical_summary?: string | null;
  documentation_approved_date?: string | null;
}

export type InsertStockProposal = Omit<StockProposal, 'id' | 'created_at' | 'updated_at' | 'agency_id' | 'created_by'>;
export type UpdateStockProposal = Partial<InsertStockProposal>;
